name = "Multiknapsack"
authors = ["Jnana Sai Jagana"]

[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Gurobi = "=1.9.0"
JuMP = "=1.29.3"
julia = "1.12.2"